version: '2'

services:
  ui:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    ports:
      - 80:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker.merrett.io
      ENV_DOCKER_REGISTRY_PORT: 5000
      ENV_DOCKER_REGISTRY_USE_SSL: 1

  registry:
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /var/docker/data:/var/lib/registry
      - /var/docker/auth:/auth
      - /etc/letsencrypt/archive/docker.merrett.io:/certs
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain1.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey1.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm